[params.fuse]
  isCaseSensitive = false
  shouldSort = true
  includeMatches = true
  threshold = 0.3
  minMatchCharLength = 2
  keys = ["title", "summary", "content"]

[menu]
  [[menu.main]]
    name  = "ğŸ“š Posts"
    url   = "/posts/"
    weight = 1
  [[menu.main]]
    name  = "ğŸ·ï¸ Tags"
    url   = "/tags/"
    weight = 2
  [[menu.main]]
    name  = "ğŸ” Search"
    url   = "/search/"
    weight = 3
  [[menu.main]]
    name  = "ğŸ‘¤ About"
    url   = "/about/"
    weight = 4

[languages.zh-hant.menu]
  [[languages.zh-hant.menu.main]]
    name  = "ğŸ“š æ–‡ç« "
    url   = "/zh-hant/posts/"
    weight = 1
  [[languages.zh-hant.menu.main]]
    name  = "ğŸ·ï¸ æ¨™ç±¤"
    url   = "/zh-hant/tags/"
    weight = 2
  [[languages.zh-hant.menu.main]]
    name  = "ğŸ” æœå°‹"
    url   = "/zh-hant/search/"
    weight = 3
  [[languages.zh-hant.menu.main]]
    name  = "ğŸ‘¤ é—œæ–¼æˆ‘"
    url   = "/zh-hant/about/"
    weight = 4
