[profileMode]
enabled = true
title = "å—¨ï¼Œæˆ‘æ˜¯ Zakk"
subtitle = """ğŸ“ å¢¨çˆ¾æœ¬ ğŸ‡¦ğŸ‡º  |  â„ï¸ UTC +10 (AEST)
â¤ï¸ [@abyss_74.50](https://www.instagram.com/abyss_74.50/) âœ¨
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”
ğŸ® éŠæˆ² Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è
"""
imageURL = "https://avatars.githubusercontent.com/u/221879664?v=4"
imageWidth = 160
imageHeight = 160
imageTitle = "Zakk"

[[socialIcons]]
name = "instagram"
url  = "https://www.instagram.com/zakk.au/"

[[socialIcons]]
name = "github"
url  = "https://github.com/Zakkaus/"

[[socialIcons]]
name = "x"
url  = "https://x.com/zakkauu"
