[profileMode]
enabled = true
title = "Hi, I'm Zakk"
subtitle = """ğŸ“ Melbourne ğŸ¨  |  â„ï¸ UTC +10 (AEST)
â¤ï¸ [@abyss_74.50](https://www.instagram.com/abyss_74.50/) âœ¨
ğŸ¹ Guinea pigs ğŸ¥”
ğŸ® Gaming Â· ğŸ§ Linux Â· ğŸ’¹ Finance
"""
imageURL = "https://avatars.githubusercontent.com/u/221879664?v=4"
imageWidth = 160
imageHeight = 160
imageTitle = "Zakk"

[[socialIcons]]
name = "instagram"
url  = "https://www.instagram.com/zakk.au/"

[[socialIcons]]
name = "github"
url  = "https://github.com/Zakkaus/"

[[socialIcons]]
name = "x"
url  = "https://x.com/zakkauu"
